-- Populate retreat configurations with proper UUIDs
INSERT INTO public.retreat_configurations (
  id, name, slug, description, short_description, duration_days, 
  focus_areas, principles, target_conditions, contraindications, 
  risk_level, requires_supervision, evidence_based_therapies, is_active
) VALUES 
(
  gen_random_uuid(),
  'Inner Compass: Stress Recovery Retreat',
  'stress-recovery',
  'A comprehensive 7-day program designed to help individuals recover from chronic stress using evidence-based mindfulness, somatic therapy, and cognitive behavioral techniques.',
  'Evidence-based stress recovery through mindfulness and somatic practices',
  7,
  ARRAY['Stress Management', 'Mindfulness', 'Somatic Awareness', 'Cognitive Flexibility'],
  ARRAY['Trauma-informed care', 'Gentle progression', 'Body-based healing', 'Mindful awareness'],
  ARRAY['Chronic stress', 'Burnout', 'Anxiety', 'Sleep difficulties'],
  ARRAY['Active psychosis', 'Severe dissociation', 'Acute suicidal ideation'],
  'low',
  false,
  ARRAY['Mindfulness-Based Stress Reduction (MBSR)', 'Somatic Experiencing', 'Cognitive Behavioral Therapy (CBT)'],
  true
),
(
  gen_random_uuid(),
  'Steady Ground: Anxiety Relief & Resilience',
  'anxiety-relief', 
  'A 10-day evidence-based program combining CBT, mindfulness, and exposure therapy techniques to build resilience and reduce anxiety symptoms.',
  'Evidence-based anxiety relief through CBT and mindfulness practices',
  10,
  ARRAY['Anxiety Management', 'Cognitive Restructuring', 'Mindfulness', 'Exposure Therapy'],
  ARRAY['Evidence-based practice', 'Gradual exposure', 'Cognitive flexibility', 'Mindful awareness'],
  ARRAY['Generalized anxiety', 'Social anxiety', 'Panic disorder', 'Phobias'],
  ARRAY['Active psychosis', 'Severe agoraphobia', 'Acute suicidal ideation'],
  'moderate',
  false,
  ARRAY['Cognitive Behavioral Therapy (CBT)', 'Mindfulness-Based Cognitive Therapy (MBCT)', 'Exposure and Response Prevention (ERP)'],
  true
),
(
  gen_random_uuid(),
  'Gentle Dawn: Depression Support & Healing',
  'depression-support',
  'A 14-day therapeutic program using evidence-based approaches including behavioral activation, mindfulness, and gentle movement to support depression recovery.',
  'Gentle, evidence-based approach to depression support and healing',
  14,
  ARRAY['Depression Support', 'Behavioral Activation', 'Mindfulness', 'Gentle Movement'],
  ARRAY['Gentle progression', 'Behavioral activation', 'Mindful awareness', 'Self-compassion'],
  ARRAY['Major depression', 'Persistent depressive disorder', 'Seasonal depression'],
  ARRAY['Active suicidal ideation', 'Severe psychosis', 'Active substance abuse'],
  'moderate',
  true,
  ARRAY['Behavioral Activation Therapy (BAT)', 'Mindfulness-Based Cognitive Therapy (MBCT)', 'Acceptance and Commitment Therapy (ACT)'],
  true
),
(
  gen_random_uuid(),
  'Safe Harbor: PTSD Recovery & Integration',
  'ptsd-recovery',
  'A specialized 21-day trauma-informed program using EMDR, somatic experiencing, and mindfulness to support PTSD recovery in a safe, gradual manner.',
  'Trauma-informed PTSD recovery through EMDR and somatic practices',
  21,
  ARRAY['Trauma Recovery', 'EMDR', 'Somatic Experiencing', 'Safety Building'],
  ARRAY['Trauma-informed care', 'Safety first', 'Window of tolerance', 'Gentle progression'],
  ARRAY['PTSD', 'Complex trauma', 'Acute stress disorder'],
  ARRAY['Active psychosis', 'Severe dissociation', 'Active substance abuse', 'Acute suicidal ideation'],
  'high',
  true,
  ARRAY['Eye Movement Desensitization and Reprocessing (EMDR)', 'Somatic Experiencing', 'Trauma-Focused CBT'],
  true
),
(
  gen_random_uuid(),
  'Reset Path: Corporate Burnout Recovery',
  'corporate-burnout',
  'A 14-day intensive program specifically designed for corporate burnout recovery, combining stress management, boundary setting, and career realignment strategies.',
  'Comprehensive corporate burnout recovery and prevention program',
  14,
  ARRAY['Burnout Recovery', 'Stress Management', 'Boundary Setting', 'Work-Life Balance'],
  ARRAY['Sustainable practices', 'Boundary awareness', 'Value alignment', 'Mindful leadership'],
  ARRAY['Burnout', 'Work stress', 'Career transition', 'Leadership stress'],
  ARRAY['Active psychosis', 'Severe depression', 'Acute suicidal ideation'],
  'moderate',
  false,
  ARRAY['Acceptance and Commitment Therapy (ACT)', 'Mindfulness-Based Stress Reduction (MBSR)', 'Values-Based Action'],
  true
),
(
  gen_random_uuid(),
  'Sacred Journey: Grief & Loss Healing',
  'grief-healing',
  'A 21-day compassionate program supporting individuals through grief and loss using evidence-based approaches including grief therapy, mindfulness, and creative expression.',
  'Compassionate grief support through evidence-based healing practices',
  21,
  ARRAY['Grief Processing', 'Loss Integration', 'Meaning Making', 'Creative Expression'],
  ARRAY['Compassionate presence', 'Meaning making', 'Creative expression', 'Community support'],
  ARRAY['Bereavement', 'Loss', 'Complicated grief', 'Anticipatory grief'],
  ARRAY['Active suicidal ideation', 'Severe psychosis', 'Active substance abuse'],
  'moderate',
  true,
  ARRAY['Grief Therapy', 'Narrative Therapy', 'Expressive Arts Therapy', 'Mindfulness-Based Approaches'],
  true
);

-- Now create comprehensive daily activities for stress recovery retreat (2 sessions per day)
WITH stress_retreat AS (
  SELECT id FROM retreat_configurations WHERE slug = 'stress-recovery'
)
INSERT INTO public.retreat_activities (
  retreat_id, day_number, time_slot, activity_name, activity_type, 
  description, instructions, duration_minutes, evidence_base, 
  trauma_considerations, difficulty_level
) 
SELECT 
  sr.id,
  day_data.day_number,
  day_data.time_slot,
  day_data.activity_name,
  day_data.activity_type,
  day_data.description,
  day_data.instructions,
  day_data.duration_minutes,
  day_data.evidence_base,
  day_data.trauma_considerations,
  day_data.difficulty_level
FROM stress_retreat sr,
(VALUES 
  -- Day 1: Foundation & Assessment
  (1, 'morning', 'Welcome & Stress Assessment', 'reflection',
   'Comprehensive welcome session including stress level assessment and program orientation.',
   'Complete initial stress questionnaires, set intentions, and learn about the program structure.',
   45, 'Perceived Stress Scale (PSS), evidence-based stress assessment tools',
   ARRAY['Gentle introduction', 'Choice and consent emphasized', 'Safe space creation'],
   'beginner'),
  (1, 'evening', 'Introduction to Mindful Breathing', 'mindfulness',
   'Learn foundational breathing techniques for immediate stress relief.',
   'Practice 4-7-8 breathing, box breathing, and natural breath awareness in comfortable position.',
   30, 'Mindfulness-Based Stress Reduction (MBSR) breathing protocols',
   ARRAY['Option to keep eyes open', 'Permission to adjust position', 'No forced breathing'],
   'beginner'),
  -- Day 2: Body Awareness
  (2, 'morning', 'Body Scan for Stress Release', 'mindfulness',
   'Progressive body scan meditation to identify and release physical tension.',
   'Guided body scan from toes to head, noticing sensations without judgment.',
   35, 'MBSR body scan meditation protocol',
   ARRAY['Option to skip uncomfortable areas', 'Permission to move as needed'],
   'beginner'),
  (2, 'evening', 'Gentle Movement Therapy', 'movement',
   'Trauma-informed gentle movement to release stored stress in the body.',
   'Simple stretches, gentle yoga poses, and intuitive movement guided by body wisdom.',
   40, 'Trauma-Sensitive Yoga principles',
   ARRAY['All movements optional', 'Stop anytime', 'Listen to body signals'],
   'beginner'),
  -- Day 3: Cognitive Awareness
  (3, 'morning', 'Stress Thought Patterns Recognition', 'reflection',
   'Identify and understand personal stress-inducing thought patterns.',
   'Journal about stress triggers, notice thought patterns, learn cognitive awareness techniques.',
   40, 'Cognitive Behavioral Therapy (CBT) thought monitoring',
   ARRAY['No judgment of thoughts', 'Observation only', 'Self-compassion emphasized'],
   'intermediate'),
  (3, 'evening', 'Progressive Muscle Relaxation', 'healing',
   'Evidence-based muscle relaxation technique for deep stress release.',
   'Systematic tensing and releasing of muscle groups with guided instruction.',
   30, 'Jacobson Progressive Muscle Relaxation protocol',
   ARRAY['Option to skip muscle tension', 'Focus on release only if needed'],
   'beginner'),
  -- Day 4: Emotional Regulation
  (4, 'morning', 'Mindful Emotional Awareness', 'mindfulness',
   'Develop skills to observe and regulate emotions mindfully.',
   'Practice RAIN technique (Recognize, Allow, Investigate, Nurture) with current emotions.',
   35, 'Mindfulness-Based Emotional Regulation techniques',
   ARRAY['No forced emotional processing', 'Permission to pause anytime'],
   'intermediate'),
  (4, 'evening', 'Stress-Relief Visualization', 'healing',
   'Guided imagery for deep relaxation and stress relief.',
   'Peaceful place visualization with all senses engaged for deep relaxation.',
   25, 'Clinical guided imagery protocols for stress reduction',
   ARRAY['Create own safe place', 'Option to keep eyes open'],
   'beginner'),
  -- Day 5: Resilience Building
  (5, 'morning', 'Building Stress Resilience', 'reflection',
   'Learn evidence-based strategies for long-term stress resilience.',
   'Explore personal resilience factors, create resilience toolkit, practice stress inoculation.',
   45, 'Stress Inoculation Training (SIT) principles',
   ARRAY['Focus on existing strengths', 'Gradual skill building'],
   'intermediate'),
  (5, 'evening', 'Nature Connection Practice', 'nature',
   'Connect with nature for natural stress relief and grounding.',
   'Mindful nature observation, earthing practice, or indoor nature meditation.',
   30, 'Ecotherapy and nature-based stress reduction research',
   ARRAY['Indoor alternatives available', 'Adapt to comfort level'],
   'beginner'),
  -- Day 6: Integration
  (6, 'morning', 'Mindful Daily Living', 'mindfulness',
   'Integrate mindfulness into daily activities and routines.',
   'Practice mindful eating, walking, and routine activities with full attention.',
   40, 'Mindfulness in daily life applications from MBSR',
   ARRAY['Choose familiar activities', 'No performance pressure'],
   'intermediate'),
  (6, 'evening', 'Self-Compassion Practice', 'healing',
   'Develop self-compassion skills for stress recovery and prevention.',
   'Learn Kristin Neff self-compassion practices including self-kindness meditation.',
   35, 'Mindful Self-Compassion (MSC) evidence-based practices',
   ARRAY['Gentle approach to self-relationship', 'No forced forgiveness'],
   'intermediate'),
  -- Day 7: Completion & Future Planning
  (7, 'morning', 'Personal Stress Management Plan', 'reflection',
   'Create personalized, sustainable stress management plan for ongoing wellness.',
   'Review learned techniques, identify favorites, create daily/weekly practice schedule.',
   50, 'Behavior change and maintenance strategies from health psychology',
   ARRAY['Realistic goal setting', 'Built-in flexibility'],
   'intermediate'),
  (7, 'evening', 'Gratitude & Completion Ceremony', 'reflection',
   'Celebrate progress and set intentions for continued growth.',
   'Reflect on journey, express gratitude, set future intentions in ceremonial format.',
   30, 'Gratitude practice research and completion ritual benefits',
   ARRAY['Participate at comfort level', 'Honor all experiences'],
   'beginner')
) AS day_data(day_number, time_slot, activity_name, activity_type, description, instructions, duration_minutes, evidence_base, trauma_considerations, difficulty_level);