// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cexzvbjpuourvxdvadec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNleHp2YmpwdW91cnZ4ZHZhZGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDg0MDAsImV4cCI6MjA2NzY4NDQwMH0.PWZUyxzjjr0RXoj1ydaMSki4lDFmtIqzxgNDxtMiFn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});